### ISSUE TITLE
尽可能不要将文件名写死在代码中

### ISSUE THREAD

**Issue by Zhang-Tianxu** [iriszuo/QuantitativeInvestment#8]
https://github.com/iriszuo/QuantitativeInvestment/blob/028086cf42b8ce1de331e19bda3c2c1127b55142/stockClass.py#L41
这行代码，将文件名`stock_data_kline.pkl`写死在代码中，这大大影响了灵活性。
@iriszuo

**Comment by iriszuo** [comment]
是的，好多地方为了简单测试一下，就这么写了，未来要做得更规范。用args输入进去？

**Comment by Zhang-Tianxu** [comment]
而且你这么写的话，每次初始化都要读取`stock+data_kline.pkl`这个巨大的文件，怪不得测试这么慢:joy:

**Comment by iriszuo** [comment]
所以我搞了两种方式，如果初始化类的时候传入了dict，那么就不用每次读取，直接用dict。只有初始化类的时候什么参数都没有才会读取本地文件

**Comment by Zhang-Tianxu** [comment]
> 是的，好多地方为了简单测试一下，就这么写了，未来要做得更规范。用args输入进去？

我觉得，构造函数的输入就是一个list，至于list从哪里来，这个不是stock类要考虑的，而是调用这个类的人要考虑的。

```python
def __init__(self, code, stock_data=[]):
    if(len(stock_data) > 0):
        # 利用stock_data初始化该股票
    else:
        # 没有给数据，根据code从网上获取数据，进而初始化该股票
```

**Comment by iriszuo** [comment]
讨论结果：改为
`def __init__(self, stock_data):
stock_data是dataframe格式的csv内容`
待改。

**Comment by iriszuo** [comment]
dev_1最新commit已解决该问题。
