### ISSUE TITLE
回测过程中，测试进程不应该因为某个股票的测试失败而崩溃。而是应该记录测试失败的股票，继续完成剩余测试。

### ISSUE THREAD

**Issue by Zhang-Tianxu** [iriszuo/QuantitativeInvestment#9]
如题，另外需要：
1. 做好Log
2. 以追加的方式记录测试结果

**Comment by iriszuo** [comment]
dev1的最新commit已解决该问题：
1. 添加了失败继续功能
2. 添加了失败log存储到文件error.txt功能
3. 以追加方式在csv记录结果。
